export const USER_ACTION_TYPES = {
    // SET_CURRENT_USER: "SET_CURRENT_USER",
    USER_SIGN_IN_UP_START: "USER_SIGN_IN_UP_START",
    USER_SIGN_IN_UP_SUCCESS: "USER_SIGN_IN_UP_SUCCESS",
    USER_SIGN_IN_UP_FAILED: "USER_SIGN_IN_UP_FAILED",

}


// export const USER_ACTION_TYPES = {
//     SET_CURRENT_USER: "user/SET_CURRENT_USER"
// }   